package com.rafaelsdiamonds.taskmaster;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.location.Address;
import android.location.Geocoder;
import android.location.Location;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.Toast;

import com.amazonaws.mobile.client.AWSMobileClient;
import com.amazonaws.amplify.generated.graphql.CreateTaskMutation;
import com.amazonaws.amplify.generated.graphql.ListTeamsQuery;
import com.amazonaws.mobile.config.AWSConfiguration;
import com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient;
import com.amazonaws.mobileconnectors.s3.transferutility.TransferListener;
import com.amazonaws.mobileconnectors.s3.transferutility.TransferObserver;
import com.amazonaws.mobileconnectors.s3.transferutility.TransferState;
import com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.s3.model.CannedAccessControlList;
import com.apollographql.apollo.GraphQLCall;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.exception.ApolloException;
import com.google.android.gms.location.FusedLocationProviderClient;
import com.google.android.gms.location.LocationServices;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.UUID;

import javax.annotation.Nonnull;

import type.CreateTaskInput;

public class AddTask extends AppCompatActivity {

    private static final int MY_PERMISSIONS_REQUEST_READ_CONTACTS = 1;
    private FusedLocationProviderClient fusedLocationClient;
    Bitmap bitmap;
    private AWSAppSyncClient mAWSAppSyncClient;
    int SELECTED_PHOTO = 1;
    Uri uri;
    RadioButton radioButton;
    int[] buttons = new int[3];
    RadioGroup radioGroup;
    int teamPepsiRadioButtonId;
    int teamSpriteRadioButtonId;
    int teamCokeRadioButtonId;
    private AmazonS3Client amazonS3Client;
    private UUID uuid;
    private String imgUrl;
    private String userLocation;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_addtask);

        fusedLocationClient = LocationServices.getFusedLocationProviderClient(this);
        // create the location service client.
        askForPermission();


        //gets a random name for uploaded file
        // radiogroup assigning ids to random numbers generated by RadioGroupView
        radioGroup = (RadioGroup) findViewById(R.id.taskTeamRadioGroup);

        Intent externalIntent = getIntent();
        if (externalIntent.getType() != null) {
            if (externalIntent.getType().indexOf("image/") != -1) {
                Bundle bundle = externalIntent.getExtras();
                uri = (Uri) bundle.get(Intent.EXTRA_STREAM);
                onImportResult();
            } else {
                Toast.makeText(getApplicationContext(), "Invalid Image!", Toast.LENGTH_LONG).show();
            }
        }

        int radioGroupSize = radioGroup.getChildCount();
        buttons[0] = teamPepsiRadioButtonId;
        buttons[1] = teamSpriteRadioButtonId;
        buttons[2] = teamCokeRadioButtonId;

        for (int i = 0; i < radioGroupSize; i++) {
            buttons[i] = radioGroup.getChildAt(i).getId();
        }


        Button uploadButton = findViewById(R.id.uploadButton);
        uploadButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(Intent.ACTION_PICK);
                intent.setType("image/*");
                startActivityForResult(intent, SELECTED_PHOTO);
            }
        });

        mAWSAppSyncClient = AWSAppSyncClient.builder()
                .context(getApplicationContext())
                .awsConfiguration(new AWSConfiguration(getApplicationContext()))
                .build();


        ListTeamsQuery teams = ListTeamsQuery.builder().build();
        final HashMap<String, String> teamHashmap = new HashMap<>();
        mAWSAppSyncClient.query(teams).enqueue(new GraphQLCall.Callback<ListTeamsQuery.Data>() {
            @Override
            public void onResponse(@Nonnull Response<ListTeamsQuery.Data> response) {
                for (ListTeamsQuery.Item team : response.data().listTeams().items()) {
                    teamHashmap.put(team.name(), team.id());
                }
            }

            @Override
            public void onFailure(@Nonnull ApolloException e) {
                Log.i("ran", "failed to pull from db");
            }
        });


        radioGroup.setOnCheckedChangeListener(new RadioGroup.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(RadioGroup group, int checkedId) {

            }
        });

        Button b = findViewById(R.id.saveTaskToDbButton);

        b.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {


                int selectedId = radioGroup.getCheckedRadioButtonId();

                // determining the string value of radio button based on auto generated id number of radio number.
                String selectedTeamTextToChange = "teamPepsi";
                if (selectedId == buttons[0]) {
                    selectedTeamTextToChange = "teamPepsi";
                } else if (selectedId == buttons[1]) {
                    selectedTeamTextToChange = "teamSprite";
                } else if (selectedId == buttons[2]) {
                    selectedTeamTextToChange = "teamCoke";
                }
                EditText taskTitle = findViewById(R.id.addTaskTitle);
                EditText taskBody = findViewById(R.id.addTaskBody);
                setContentView(R.layout.activity_main);
                Log.e("rvrv", selectedTeamTextToChange);


                if (taskTitle.getText().toString().isEmpty()) {
                    taskTitle.setError("Field Required");
                    Toast.makeText(getApplicationContext(), "Task Title Missing", Toast.LENGTH_SHORT).show();

                }
                if (taskBody.getText().toString().isEmpty()) {
                    taskTitle.setError("Field Required");
                    Toast.makeText(getApplicationContext(), "Task Body Missing", Toast.LENGTH_SHORT).show();
                }

                if (imgUrl == null || imgUrl.equals("")) {
                    taskTitle.setError("Field Required");
                    Toast.makeText(getApplicationContext(), "Picture Needed", Toast.LENGTH_SHORT).show();
                }

                CreateTaskInput createTaskInput = CreateTaskInput.builder()
                        .title(taskTitle.getText().toString())
                        .body(taskBody.getText().toString())
                        .taskTeamId(teamHashmap.get(selectedTeamTextToChange))
                        .state("new")
                        .image(imgUrl)
                        .location(userLocation)
                        .build();


                mAWSAppSyncClient.mutate(CreateTaskMutation.builder().input(createTaskInput).build()).enqueue(
                        new GraphQLCall.Callback<CreateTaskMutation.Data>() {
                            @Override
                            public void onResponse(@Nonnull Response<CreateTaskMutation.Data> response) {
                                Log.e("rvrv", response.data().toString());
                            }

                            @Override
                            public void onFailure(@Nonnull ApolloException e) {
                                Log.e("rvrv", "failed to save to database");
                            }
                        }
                );
                finish();
            }


        });

    }

    private void askForPermission() {
        if (ContextCompat.checkSelfPermission(this,
                Manifest.permission.ACCESS_FINE_LOCATION)
                != PackageManager.PERMISSION_GRANTED) {

            // Permission is not granted
            // Should we show an explanation?
            if (ActivityCompat.shouldShowRequestPermissionRationale(this,
                    Manifest.permission.ACCESS_FINE_LOCATION)) {
                // Show an explanation to the user *asynchronously* -- don't block
                // this thread waiting for the user's response! After the user
                // sees the explanation, try again to request the permission.
            } else {
                // No explanation needed; request the permission
                ActivityCompat.requestPermissions(this,
                        new String[]{Manifest.permission.ACCESS_FINE_LOCATION},
                        MY_PERMISSIONS_REQUEST_READ_CONTACTS);
                // MY_PERMISSIONS_REQUEST_READ_CONTACTS is an
                // app-defined int constant. The callback method gets the
                // result of the request.
            }
        } else {
            // Permission has already been granted
            fusedLocationClient.getLastLocation()
                    .addOnSuccessListener(AddTask.this, new OnSuccessListener<Location>() {
                        @Override
                        public void onSuccess(Location location) {
                            if (location != null) {
                                Log.i("rvrv", "location received");
                                double longitude = location.getLongitude();
                                double latitude = location.getLatitude();

                                // covert coordinates to geolocation https://www.youtube.com/watch?v=Ut_VK92QqEQ
                                Geocoder geocoder = new Geocoder(getApplicationContext(), Locale.getDefault());
                                try {
                                    List<Address> address = geocoder.getFromLocation(latitude,longitude,1);
                                    userLocation = address.get(0).getAddressLine(0);
                                    System.out.println("userLocation = " + userLocation);
                                } catch (IOException e) {
                                    e.printStackTrace();
                                }
                            }
                        }
                    })
                    .addOnFailureListener(new OnFailureListener() {
                        @Override
                        public void onFailure(@NonNull Exception e) {
                            Log.i("rvrv", "invalid location");
                            e.printStackTrace();
                        }
                    });

        }
    }

    public void uploadWithTransferUtility() {

        TransferUtility transferUtility =
                TransferUtility.builder()
                        .context(getApplicationContext())
                        .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
                        .s3Client(new AmazonS3Client(AWSMobileClient.getInstance()))
                        .build();


        uuid = UUID.randomUUID();
        String filename = uuid + ".png";
        File f = new File(getApplicationContext().getFilesDir(), filename);
        try {
            f.createNewFile();
            //Convert bitmap to byte array
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            bitmap.compress(Bitmap.CompressFormat.JPEG, 100, bos);
            byte[] bitmapData = bos.toByteArray();

            //write the bytes in file
            FileOutputStream fos = new FileOutputStream(f);
            fos.write(bitmapData);
            fos.flush();
            fos.close();
        } catch (Exception e) {
            e.printStackTrace();
        }


        TransferObserver uploadObserver =
                transferUtility.upload(
                        "public/" + filename,
                        new File(getApplicationContext().getFilesDir(), filename), CannedAccessControlList.PublicRead);

        // Attach a listener to the observer to get state update and progress notifications
        uploadObserver.setTransferListener(new TransferListener() {

            @Override
            public void onStateChanged(int id, TransferState state) {
                Log.i("rvrv", "state changed to " + state);
                if (TransferState.COMPLETED == state) {
                    // Handle a completed upload.
                }
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                float percentDonef = ((float) bytesCurrent / (float) bytesTotal) * 100;
                int percentDone = (int) percentDonef;

                Log.d("rvrv", "ID:" + id + " bytesCurrent: " + bytesCurrent
                        + " bytesTotal: " + bytesTotal + " " + percentDone + "%");
            }

            @Override
            public void onError(int id, Exception ex) {
                // Handle errors
                Log.e("rvrv", ex.toString());
            }

        });

        // If you prefer to poll for the data, instead of attaching a
        // listener, check for the state and progress in the observer.
        if (TransferState.COMPLETED == uploadObserver.getState()) {
            // Handle a completed upload.
        }

        Log.d("rvrv", "Bytes Transferred: " + uploadObserver.getBytesTransferred());
        Log.d("rvrv", "Bytes Total: " + uploadObserver.getBytesTotal());
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == SELECTED_PHOTO && resultCode == RESULT_OK && data != null && data.getData() != null) {
            uri = data.getData();
            try {
                bitmap = MediaStore.Images.Media.getBitmap(getContentResolver(), uri);
                uploadWithTransferUtility();
                imgUrl = "https://taskmaster101433-taskmaster.s3.us-east-2.amazonaws.com/public/" + uuid + ".png";


            } catch (Exception e) {
                Log.e("rvrv", e.toString());
                e.printStackTrace();
            }
        }
    }

    protected void onImportResult() {
        try {
            bitmap = MediaStore.Images.Media.getBitmap(getContentResolver(), uri);
            uploadWithTransferUtility();
            imgUrl = "https://taskmaster101433-taskmaster.s3.us-east-2.amazonaws.com/public/" + uuid + ".png";


        } catch (Exception e) {
            Log.e("rvrv", e.toString());
            e.printStackTrace();
        }
    }
}
